Feature: Save and delete comments with graphql mutations
Rocketseat/live-graphql pull request #3
Opened 2019-10-29 17:49 UTC by tuliocll

Salvar comentário e atualizar registros após o envio, adicionado também um botão para remover comentários e atualizar os dados novamente.
Adicionado também o arquivo do editorconfig e do prettierrc

2019-10-29 20:17 UTC, jpedroschmitz requested changes

2019-10-29 20:17 UTC, jpedroschmitz commented on client/.editorconfig
> +indent_size = 4
Será que teria como trocar de 4 para 2? Aqui na Rocket utilizamos 2 de espaçamento para tudo.

2019-10-29 20:17 UTC, jpedroschmitz commented on client/src/App.css
> +    box-sizing: border-box;
Nesse arquivo tudo certo, só agradeceria se pudesse corigir o espaçamento de 4 para 2 💜

2019-10-29 20:17 UTC, jpedroschmitz commented on client/src/components/Form.js
> +`;
Nesse arquivo, como eu fiz o merge de outra PR, essa funcionalidade de adicionar comentários não vai ser necessária.

2019-10-29 20:17 UTC, jpedroschmitz commented
Falaa @tuliocll, muito obrigado pela sua contribuição 💜 

Eu fiz o merge da PR do @felipebergamin e portanto vai ter alguns conflitos na sua branch, será que teria como você corrigir para eu possa fazer o merge dessa PR? Curti muito que você colocou o Prettier, EditorConfig e adicionou novas funcionalidades de exclusão. Deixei outros detalhes na review também, se puder ajeitar vai ajudar muito 💯 

Keep rocking 🚀

2019-10-29 21:11 UTC, tuliocll commented
Pronto @jpedroschmitz ! Acabei de fazer as alterações. Parabéns pela live cara, foi show!

2019-10-30 12:14 UTC, jpedroschmitz approved these changes
Show @tuliocll, muito obrigado pelas alterações, mandou muito 💜

2019-10-30 12:14 UTC, merged